blueprint:
  name: Mobile Notification Helper
  description: |
    This blueprint is designed to help you create automations that send mobile notifications based on button presses from remotes.
  domain: script
  author: travipross
  input:
    target_action:
      name: Target Notification Action/Service
      description: The notification service to use. Should be of the `notify` domain. The data for the service call will be overwritten when the script is called.
      selector:
        action: {}
fields:
  message:
    name: Notification Body
    required: true
    example: This is a notification message
    description: Body of notification to be sent to mobile device
    selector:
      text: {}
  title:
    name: Notification Title
    required: true
    selector:
      text: {}
  image:
    name: Notification Image
    default: ""
    selector:
      text: {}
  tag:
    name: Notification Tag
    default: GENERIC_NOTIFY
  clickAction:
    name: Click Action
    description: >-
      Action to take place upon tapping notification.
      https://companion.home-assistant.io/docs/notifications/notifications-basic?_highlight=clickaction#opening-a-url
    default: ""
    selector:
      text: {}
  actions:
    name: Actions List (Buttons)
    description: >-
      https://companion.home-assistant.io/docs/notifications/actionable-notifications
    selector:
      object: {}
    default: []
  notification_icon:
    name: Notification Icon
    default: ""
    selector:
      text: {}
  color:
    name: Notification Color
    example: red
    selector:
      color_rgb: {}
  channel:
    name: Notification Channel
    default: General
    description: Category of notification.
  sticky:
    name: Sticky?
    description: Keep notification active after tapping
    default: ""
    selector:
      boolean: {}
  persistent:
    name: Persistent?
    description: Disallow notification from being dismissed
    selector:
      boolean: {}
  critical:
    name: Critical?
    default: true
    description: >-
      Sets ttl=0, priority=high for immediate delivery.
      https://companion.home-assistant.io/docs/notifications/critical-notifications
    selector:
      boolean: {}
  alert_once:
    name: Alert Once?
    description: >-
      Only trigger sound/vibration/LED on receiving device for the first
      instance (allows dynamic updating)
    default: ""
    selector:
      boolean: {}
sequence:
  - variables:
      action_selection: !input target_action
      action_data: 
        title: "{{ title }}"
        message: "{{ message }}"
        data:
          image: "{{ image }}"
          tag: "{{ tag }}"
          sticky: "{{ sticky }}"
          persistent: "{{ persistent }}"
          clickAction: "{{ clickAction }}"
          actions: "{{ actions }}"
          notification_icon: "{{ notification_icon }}"
          color: "{{ color }}"
          channel: "{{ channel }}"
          ttl: "{{  0 if critical else '' }}"
          priority: "{{ 'high' if critical else 'normal' }}"
          alert_once: "{{ alert_once }}"
  - action: "{{ action_selection.0.action }}"
    metadata: {}
    data: "{{ action_data }}"
